// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fktypuczzzhenvmibgti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrdHlwdWN6enpoZW52bWliZ3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MTc3NjgsImV4cCI6MjA1MDk5Mzc2OH0.zpjdxZHk-H9UP0Qe9ZLIzV-ddRIlwtnde_iQAGvTUJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);